[package]
name = "moce"
version = "0.1.0"
authors = ["KISHI Kousuke <ksh2ksk4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
